on: push

jobs:
  default:
    strategy:
      matrix:
        os: [macos-11]
        python-version: ['3.8']
        pip-lxml-flags: ['--only-binary=lxml', '--no-binary=lxml']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: sudo apt install -y libxml2-dev libxslt1-dev
      - run: pip install ${{ matrix.pip-lxml-flags }} lxml==4.9.1
      - run: python -m unittest
